#ifndef __CONTROL_PANEL_H
#define __CONTROL_PANEL_H

#define FINE_CALIBRATED_H_MIN 54
#define FINE_CALIBRATED_H_MAX 96
#define FINE_CALIBRATED_S_MIN 54
#define FINE_CALIBRATED_S_MAX 256
#define FINE_CALIBRATED_V_MIN 0
#define FINE_CALIBRATED_V_MAX 256

#endif
